package com.formos.huub.domain.constant;

import com.formos.huub.domain.enums.QuestionTypeEnum;

import java.util.*;

public final class FormConstant {

    public static final String PARAM_PORTAL_NAME = "{Portal Name}";
    public static final String PARAM_PROGRAM_NAME = "{Program Name}";
    public static final String PARAM_PORTAL_PRIMARY_CONTACT_NAME = "{Portal Primary Contact Name}";
    public static final String PARAM_PORTAL_PRIMARY_CONTACT_EMAIL = "{Portal Primary Contact Email}";
    public static final String PARAM_PORTAL_PRIMARY_CONTACT_PHONE = "{Portal Primary Contact Phone}";
    public static final String PARAM_PORTAL_CITY = "{City/Region}";
    public static final String ANSWER_YES = "Yes";
    public static final String QUESTION_OTHER = "_OTHER";
    public static final String ANSWER_NO = "No";
    public static final UUID ANSWER_OTHER_ID = UUID.fromString("c4611303-1179-4c6d-bd01-be14159b48a8");
    public static final Integer MAX_PORTAL_ADDITIONAL_QUESTION = 5;
    public static final Integer MAX_TECHNICAL_ASSISTANCE_ADDITIONAL_QUESTION = 10;
    public static final String COLUMN_SIZE_12 = "12";
    public static final String PORTAL_INTAKE_ADDITIONAL_QUESTION = "PORTAL_INTAKE_ADDITIONAL_QUESTION";
    public static final String PLACEHOLDER_TEXT = "Enter some text...";
    public static final String PLACEHOLDER_SINGLE_CHOICE = "Select one...";
    public static final String PLACEHOLDER_MULTI_CHOICE = "Select all that apply...";
    public static final String PLACEHOLDER_DATE = "Choose a date...";
    public static final String KEY_STEP = "step%s";

    public static final String BUSINESS_OWNER_FORM = "BUSINESS_OWNER_FORM";
    public static final String BUSINESS_OWNER_DETAILS_MODAL = "BUSINESS_OWNER_DETAILS_MODAL";

    public static final Map<QuestionTypeEnum, String> PLACEHOLDER_MAP = Map.of(
        QuestionTypeEnum.TEXT, FormConstant.PLACEHOLDER_TEXT,
        QuestionTypeEnum.TEXT_AREA, FormConstant.PLACEHOLDER_TEXT,
        QuestionTypeEnum.DATE_PICKER, FormConstant.PLACEHOLDER_DATE,
        QuestionTypeEnum.DROPDOWN_MULTIPLE_CHOICE, FormConstant.PLACEHOLDER_MULTI_CHOICE,
        QuestionTypeEnum.DROPDOWN_SINGLE_CHOICE, FormConstant.PLACEHOLDER_SINGLE_CHOICE
    );


    //    Question constant in demographic page
    public static final String QUESTION_LANGUAGE_SPOKEN = "QUESTION_LANGUAGE_SPOKEN";
    public static final String QUESTION_OTHER_LANGUAGE_SPOKEN = "QUESTION_OTHER_LANGUAGE_SPOKEN";
    public static final String QUESTION_ETHNICITY = "QUESTION_ETHNICITY";
    public static final String QUESTION_OTHER_ETHNICITY = "QUESTION_OTHER_ETHNICITY";
    public static final String QUESTION_GENDER_IDENTITY = "QUESTION_GENDER_IDENTITY";
    public static final String QUESTION_OTHER_GENDER_IDENTITY = "QUESTION_OTHER_GENDER_IDENTITY";
    public static final String QUESTION_MILITARY_AFFILIATION = "QUESTION_MILITARY_AFFILIATION";
    public static final String QUESTION_LGBTQ_IDENTIFICATION = "QUESTION_LGBTQ_IDENTIFICATION";
    public static final String QUESTION_DISABILITY_STATUS = "QUESTION_DISABILITY_STATUS";
    public static final String QUESTION_CONSULTING_RATES = "QUESTION_CONSULTING_RATES";
    public static final String QUESTION_YES_NO = "QUESTION_YES_NO";

    //    Question constant in Portal Intake business page

    public static final String QUESTION_BUSINESS_STRUCTURE = "QUESTION_BUSINESS_STRUCTURE";
    public static final String QUESTION_BUSINESS_REGISTRATION = "QUESTION_BUSINESS_REGISTRATION";
    public static final String QUESTION_BUSINESS_OPENING_DATE = "QUESTION_BUSINESS_OPENING_DATE";
    public static final String QUESTION_BUSINESS_INDUSTRY_INFORMATION = "QUESTION_BUSINESS_INDUSTRY_INFORMATION";
    public static final String QUESTION_BUSINESS_REVENUE_INFORMATION_ONE_YEAR = "QUESTION_BUSINESS_REVENUE_INFORMATION_ONE_YEAR";
    public static final String QUESTION_BUSINESS_REVENUE_INFORMATION_TOW_YEAR = "QUESTION_BUSINESS_REVENUE_INFORMATION_TOW_YEAR";
    public static final String QUESTION_BUSINESS_EMPLOYEE_COUNT = "QUESTION_BUSINESS_EMPLOYEE_COUNT";
    public static final String QUESTION_BUSINESS_HOME_BASED_LOCATION = "QUESTION_BUSINESS_HOME_BASED_LOCATION";
    public static final String QUESTION_BUSINESS_HOW_MANY_LOCATIONS = "QUESTION_BUSINESS_HOW_MANY_LOCATIONS";
    public static final String QUESTION_BUSINESS_HAVE_MORE_THAN_ONE_LOCATION_IN_CITY = "QUESTION_BUSINESS_HAVE_MORE_THAN_ONE_LOCATION_IN_CITY";
    public static final String QUESTION_BUSINESS_DURATION = "QUESTION_BUSINESS_DURATION";
    public static final String QUESTION_BUSINESS_STATUS = "QUESTION_BUSINESS_STATUS";

    // Questions constant in Portal Intake profile page
    public static final String PORTAL_INTAKE_QUESTION_FIRST_NAME = "PORTAL_INTAKE_QUESTION_FIRST_NAME";
    public static final String PORTAL_INTAKE_QUESTION_LAST_NAME = "PORTAL_INTAKE_QUESTION_LAST_NAME";
    public static final String PORTAL_INTAKE_QUESTION_EMAIL_ADDRESS = "PORTAL_INTAKE_QUESTION_EMAIL_ADDRESS";
    public static final String PORTAL_INTAKE_QUESTION_PHONE_NUMBER = "PORTAL_INTAKE_QUESTION_PHONE_NUMBER";
    public static final String PORTAL_INTAKE_QUESTION_JOB_TITLE = "PORTAL_INTAKE_QUESTION_JOB_TITLE";
    public static final String PORTAL_INTAKE_QUESTION_PREFER_CONTACTED = "PORTAL_INTAKE_QUESTION_PREFER_CONTACTED";
    public static final String PORTAL_INTAKE_QUESTION_HEAR_ABOUT_PROGRAM = "PORTAL_INTAKE_QUESTION_HEAR_ABOUT_PROGRAM";
    public static final String PORTAL_INTAKE_QUESTION_HEAR_ABOUT_PROGRAM_OTHER = "PORTAL_INTAKE_QUESTION_HEAR_ABOUT_PROGRAM_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_BUSINESS = "PORTAL_INTAKE_QUESTION_BUSINESS";
    public static final String PORTAL_INTAKE_QUESTION_COUNTRY = "PORTAL_INTAKE_QUESTION_COUNTRY";
    public static final String PORTAL_INTAKE_QUESTION_STATE_PROVINCE = "PORTAL_INTAKE_QUESTION_STATE_PROVINCE";
    public static final String PORTAL_INTAKE_QUESTION_CITY = "PORTAL_INTAKE_QUESTION_CITY";
    public static final String PORTAL_INTAKE_QUESTION_ZIPCODE = "PORTAL_INTAKE_QUESTION_ZIPCODE";
    public static final String PORTAL_INTAKE_QUESTION_STREET_ADDRESS = "PORTAL_INTAKE_QUESTION_STREET_ADDRESS";

    // Questions constant in Portal Intake Demographics page
    public static final String PORTAL_INTAKE_QUESTION_AGE_RANGE = "PORTAL_INTAKE_QUESTION_AGE_RANGE";
    public static final String PORTAL_INTAKE_QUESTION_GENDER = "PORTAL_INTAKE_QUESTION_GENDER";
    public static final String PORTAL_INTAKE_QUESTION_HOUSEHOLD_INCOME = "PORTAL_INTAKE_QUESTION_HOUSEHOLD_INCOME";
    public static final String PORTAL_INTAKE_QUESTION_HOW_MANY_PEOPLE = "PORTAL_INTAKE_QUESTION_HOW_MANY_PEOPLE";
    public static final String PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING = "PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING";
    public static final String PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING_OTHER = "PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_ETHNICITY = "PORTAL_INTAKE_QUESTION_ETHNICITY";
    public static final String PORTAL_INTAKE_QUESTION_EDUCATION = "PORTAL_INTAKE_QUESTION_EDUCATION";
    public static final String PORTAL_INTAKE_QUESTION_MILITARY_AFFILIATION = "PORTAL_INTAKE_QUESTION_MILITARY_AFFILIATION";
    public static final String PORTAL_INTAKE_QUESTION_LGBTQIA = "PORTAL_INTAKE_QUESTION_LGBTQIA";
    public static final String PORTAL_INTAKE_QUESTION_DISABILITY_OR_DISABILITIES = "PORTAL_INTAKE_QUESTION_DISABILITY_OR_DISABILITIES";

    // Questions constant in Portal Intake Assistance need page
    public static final String PORTAL_INTAKE_QUESTION_DESCRIBE_ASSISTANCE = "PORTAL_INTAKE_QUESTION_DESCRIBE_ASSISTANCE";
    public static final String PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA = "PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA";
    public static final String PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA = "PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA";
    public static final String PORTAL_INTAKE_QUESTION_HOW_FREE_ASSISTANCE = "PORTAL_INTAKE_QUESTION_HOW_FREE_ASSISTANCE";
    public static final String PORTAL_INTAKE_QUESTION_RESOURCE_INTERESTED = "PORTAL_INTAKE_QUESTION_RESOURCE_INTERESTED";
    public static final String PORTAL_INTAKE_QUESTION_WOULD_TOU_LIKE_APPLY_FREE_ASSISTANCE = "PORTAL_INTAKE_QUESTION_WOULD_TOU_LIKE_APPLY_FREE_ASSISTANCE";
    public static final String PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA_OTHER = "PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA_OTHER = "PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_HOW_FREE_ASSISTANCE_OTHER = "PORTAL_INTAKE_QUESTION_HOW_FREE_ASSISTANCE_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_RESOURCE_INTERESTED_OTHER = "PORTAL_INTAKE_QUESTION_RESOURCE_INTERESTED_OTHER";

    // Question constant in portal intake Support application
    public static final String PORTAL_INTAKE_QUESTION_YOUR_EIN = "PORTAL_INTAKE_QUESTION_YOUR_EIN";
    public static final String PORTAL_INTAKE_QUESTION_YOUR_BUSINESS_LICENSE = "PORTAL_INTAKE_QUESTION_YOUR_BUSINESS_LICENSE";
    public static final String PORTAL_INTAKE_QUESTION_DESCRIBE_TYPE_OF_ASSISTANCE_NEEDED = "PORTAL_INTAKE_QUESTION_DESCRIBE_TYPE_OF_ASSISTANCE_NEEDED";
    public static final String PORTAL_INTAKE_QUESTION_PREFERRED_ORGANIZATION_FOR_ASSISTANCE = "PORTAL_INTAKE_QUESTION_PREFERRED_ORGANIZATION_FOR_ASSISTANCE";
    public static final String PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE = "PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE";
    public static final String PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE_OTHER = "PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY = "PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY";
    public static final String PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY_OTHER = "PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE = "PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE";
    public static final String PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE_OTHER = "PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY = "PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY";
    public static final String PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY_OTHER = "PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY_OTHER";
    public static final String PORTAL_INTAKE_QUESTION_ADVISOR_SUPPORT_DESCRIPTION = "PORTAL_INTAKE_QUESTION_ADVISOR_SUPPORT_DESCRIPTION";

    // Question constant in portal About screen configuration
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_PAGE_TITLE = "PORTAL_ABOUT_SCREEN_CONFIGURATION_PAGE_TITLE";
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_PAGE_SUB_TITLE = "PORTAL_ABOUT_SCREEN_CONFIGURATION_PAGE_SUB_TITLE";
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_PANEL_1_TITLE = "PORTAL_ABOUT_SCREEN_CONFIGURATION_PANEL_1_TITLE";
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_PANEL_1_BODY = "PORTAL_ABOUT_SCREEN_CONFIGURATION_PANEL_1_BODY";
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_THE_PROGRAM_TITLE = "PORTAL_ABOUT_SCREEN_CONFIGURATION_THE_PROGRAM_TITLE";
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_THE_PROGRAM_BODY = "PORTAL_ABOUT_SCREEN_CONFIGURATION_THE_PROGRAM_BODY";
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_HOW_TO_APPLY = "PORTAL_ABOUT_SCREEN_CONFIGURATION_HOW_TO_APPLY";
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_TESTIMONIAL_EMBED_CODE_FIELD = "PORTAL_ABOUT_SCREEN_CONFIGURATION_TESTIMONIAL_EMBED_CODE_FIELD";
    public static final String PORTAL_ABOUT_SCREEN_CONFIGURATION_FAQS = "PORTAL_ABOUT_SCREEN_CONFIGURATION_FAQS";

    public static final List<String> LIST_QUESTION_DUPLICATE_HEADER  = new ArrayList<>();
    static {
        LIST_QUESTION_DUPLICATE_HEADER.add(FormConstant.PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY);
        LIST_QUESTION_DUPLICATE_HEADER.add(FormConstant.PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY_OTHER);
    }

    public static final List<String> LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1 = new ArrayList<>();
    static {
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1.add(PORTAL_INTAKE_QUESTION_FIRST_NAME);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1.add(PORTAL_INTAKE_QUESTION_LAST_NAME);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1.add(PORTAL_INTAKE_QUESTION_EMAIL_ADDRESS);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1.add(PORTAL_INTAKE_QUESTION_PHONE_NUMBER);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1.add(PORTAL_INTAKE_QUESTION_PREFER_CONTACTED);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1.add(PORTAL_INTAKE_QUESTION_JOB_TITLE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1.add(PORTAL_INTAKE_QUESTION_HEAR_ABOUT_PROGRAM);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1.add(PORTAL_INTAKE_QUESTION_HEAR_ABOUT_PROGRAM_OTHER);
    }

    public static final List<String> LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_2 = new ArrayList<>();

    static {
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_2.add(PORTAL_INTAKE_QUESTION_BUSINESS);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_2.add(PORTAL_INTAKE_QUESTION_COUNTRY);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_2.add(PORTAL_INTAKE_QUESTION_STATE_PROVINCE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_2.add(PORTAL_INTAKE_QUESTION_CITY);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_2.add(PORTAL_INTAKE_QUESTION_ZIPCODE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_2.add(PORTAL_INTAKE_QUESTION_STREET_ADDRESS);
    }

    public static final List<String> LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_3 = new ArrayList<>();

    static {
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_3.add(QUESTION_BUSINESS_STRUCTURE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_3.add(QUESTION_BUSINESS_REGISTRATION);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_3.add(QUESTION_BUSINESS_OPENING_DATE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_3.add(QUESTION_BUSINESS_INDUSTRY_INFORMATION);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_3.add(QUESTION_BUSINESS_REVENUE_INFORMATION_TOW_YEAR);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_3.add(QUESTION_BUSINESS_REVENUE_INFORMATION_ONE_YEAR);
    }

    public static final List<String> LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_4 = new ArrayList<>();

    static {
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_4.add(QUESTION_BUSINESS_EMPLOYEE_COUNT);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_4.add(QUESTION_BUSINESS_HOME_BASED_LOCATION);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_4.add(QUESTION_BUSINESS_HOW_MANY_LOCATIONS);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_4.add(QUESTION_BUSINESS_HAVE_MORE_THAN_ONE_LOCATION_IN_CITY);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_4.add(QUESTION_BUSINESS_DURATION);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_4.add(QUESTION_BUSINESS_STATUS);
    }

    public static final List<String> LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_5 = new ArrayList<>();

    static {
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_5.add(PORTAL_INTAKE_QUESTION_AGE_RANGE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_5.add(PORTAL_INTAKE_QUESTION_GENDER);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_5.add(PORTAL_INTAKE_QUESTION_HOUSEHOLD_INCOME);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_5.add(PORTAL_INTAKE_QUESTION_HOW_MANY_PEOPLE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_5.add(PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_5.add(PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING_OTHER);
    }

    public static final List<String> LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_6 = new ArrayList<>();

    static {
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_6.add(PORTAL_INTAKE_QUESTION_ETHNICITY);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_6.add(PORTAL_INTAKE_QUESTION_EDUCATION);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_6.add(PORTAL_INTAKE_QUESTION_MILITARY_AFFILIATION);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_6.add(PORTAL_INTAKE_QUESTION_LGBTQIA);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_6.add(PORTAL_INTAKE_QUESTION_DISABILITY_OR_DISABILITIES);
    }

    public static final List<String> LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7 = new ArrayList<>();
    static {
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7.add(PORTAL_INTAKE_QUESTION_WOULD_TOU_LIKE_APPLY_FREE_ASSISTANCE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7.add(PORTAL_INTAKE_QUESTION_RESOURCE_INTERESTED);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7.add(PORTAL_INTAKE_QUESTION_RESOURCE_INTERESTED_OTHER);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7.add(PORTAL_INTAKE_QUESTION_DESCRIBE_ASSISTANCE);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7.add(PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7.add(PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA_OTHER);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7.add(PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA);
        LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_7.add(PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA_OTHER);
    }

    public static final List<List<String>> LIST_STEPS_BUSINESS_OWNER_REGISTER_FORM = new LinkedList<>();
    static {
        LIST_STEPS_BUSINESS_OWNER_REGISTER_FORM.add(LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_1);
        LIST_STEPS_BUSINESS_OWNER_REGISTER_FORM.add(LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_2);
        LIST_STEPS_BUSINESS_OWNER_REGISTER_FORM.add(LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_3);
        LIST_STEPS_BUSINESS_OWNER_REGISTER_FORM.add(LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_4);
        LIST_STEPS_BUSINESS_OWNER_REGISTER_FORM.add(LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_5);
        LIST_STEPS_BUSINESS_OWNER_REGISTER_FORM.add(LIST_QUESTION_BUSINESS_OWNER_REGISTER_STEP_6);
    }

    public static final List<String> LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_1 = new ArrayList<>();
    static {
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_1.add(PORTAL_INTAKE_QUESTION_YOUR_EIN);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_1.add(PORTAL_INTAKE_QUESTION_YOUR_BUSINESS_LICENSE);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_1.add(PORTAL_INTAKE_QUESTION_DESCRIBE_TYPE_OF_ASSISTANCE_NEEDED);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_1.add(PORTAL_INTAKE_QUESTION_PREFERRED_ORGANIZATION_FOR_ASSISTANCE);
    }

    public static final List<String> LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2 = new ArrayList<>();
    static {
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE_OTHER);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY_OTHER);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE_OTHER);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY_OTHER);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2.add(PORTAL_INTAKE_QUESTION_ADVISOR_SUPPORT_DESCRIPTION);
    }

    public static final List<List<String>> LIST_STEPS_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_FORM = new LinkedList<>();
    static {
        LIST_STEPS_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_FORM.add(LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_1);
        LIST_STEPS_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_FORM.add(LIST_QUESTION_TECHNICAL_ASSISTANCE_APPLICATION_APPLY_STEP_2);

    }

    public static final Map<String, String> RELATED_QUESTION_CODE_MAP = new HashMap<>();
    static {
        RELATED_QUESTION_CODE_MAP.put(PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE, PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY);
        RELATED_QUESTION_CODE_MAP.put(PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE, PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY);
    }

    public static final List<String> LIST_QUESTION_DEMOGRAPHICS = new ArrayList<>();

    static {
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_LANGUAGE_SPOKEN);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_OTHER_LANGUAGE_SPOKEN);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_ETHNICITY);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_OTHER_ETHNICITY);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_GENDER_IDENTITY);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_OTHER_GENDER_IDENTITY);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_MILITARY_AFFILIATION);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_LGBTQ_IDENTIFICATION);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_DISABILITY_STATUS);
        LIST_QUESTION_DEMOGRAPHICS.add(QUESTION_CONSULTING_RATES);
    }

    public static final List<String> LIST_QUESTION_DEMOGRAPHICS_REQUIRES = new ArrayList<>();

    static {
        LIST_QUESTION_DEMOGRAPHICS_REQUIRES.add(QUESTION_CONSULTING_RATES);
        LIST_QUESTION_DEMOGRAPHICS_REQUIRES.add(QUESTION_LANGUAGE_SPOKEN);
        LIST_QUESTION_DEMOGRAPHICS_REQUIRES.add(QUESTION_ETHNICITY);
        LIST_QUESTION_DEMOGRAPHICS_REQUIRES.add(QUESTION_GENDER_IDENTITY);
        LIST_QUESTION_DEMOGRAPHICS_REQUIRES.add(QUESTION_MILITARY_AFFILIATION);
        LIST_QUESTION_DEMOGRAPHICS_REQUIRES.add(QUESTION_LGBTQ_IDENTIFICATION);
        LIST_QUESTION_DEMOGRAPHICS_REQUIRES.add(QUESTION_DISABILITY_STATUS);
    }

    public static final List<String> LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION = new ArrayList<>();

    static {
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_PAGE_TITLE);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_PAGE_SUB_TITLE);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_PANEL_1_TITLE);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_PANEL_1_BODY);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_THE_PROGRAM_TITLE);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_THE_PROGRAM_BODY);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_HOW_TO_APPLY);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_TESTIMONIAL_EMBED_CODE_FIELD);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_FAQS);
    }

    public static final List<String> LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES = new ArrayList<>();

    static {
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_PAGE_TITLE);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_PAGE_SUB_TITLE);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_PANEL_1_TITLE);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_PANEL_1_BODY);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_THE_PROGRAM_TITLE);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_THE_PROGRAM_BODY);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_HOW_TO_APPLY);
        LIST_QUESTION_ABOUT_SCREEN_CONFIGURATION_REQUIRES.add(PORTAL_ABOUT_SCREEN_CONFIGURATION_FAQS);
    }

    public static final List<String> LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN = new ArrayList<>();
    static {
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.QUESTION_BUSINESS_INDUSTRY_INFORMATION);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.QUESTION_BUSINESS_OPENING_DATE);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.QUESTION_BUSINESS_EMPLOYEE_COUNT);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.PORTAL_INTAKE_QUESTION_GENDER);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.PORTAL_INTAKE_QUESTION_ETHNICITY);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.PORTAL_INTAKE_QUESTION_MILITARY_AFFILIATION);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.PORTAL_INTAKE_QUESTION_LGBTQIA);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA);
        LIST_INTAKE_QUESTION_SYNC_ACTIVE_CAMPAIGN.add(FormConstant.PORTAL_INTAKE_QUESTION_RESOURCE_INTERESTED);
    }

}
