package com.formos.huub.domain.constant;

import com.formos.huub.domain.enums.SettingKeyCodeEnum;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public final class MemberConstant {
    public static final String FIELD ="FIELD";
    public static Map<SettingKeyCodeEnum, String> PRIVACY_SETTING_BUSINESS_MAP = new HashMap<>();
    static {
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.HUUB_PORTAL, FIELD);
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.COMPANY, FormConstant.PORTAL_INTAKE_QUESTION_BUSINESS);
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.BUSINESS_WEBSITE, FormConstant.PORTAL_INTAKE_QUESTION_EMAIL_ADDRESS);
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.DATE_BUSINESS_OPENED, FormConstant.QUESTION_BUSINESS_OPENING_DATE);
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.GENDER, FormConstant.PORTAL_INTAKE_QUESTION_GENDER);
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.FIRST_PRIORITY_ASSISTANCE, FormConstant.PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE);
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.SECOND_PRIORITY_ASSISTANCE, FormConstant.PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE);
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.WOULD_LIKE_SUPPORT_ON, FormConstant.PORTAL_INTAKE_QUESTION_DESCRIBE_TYPE_OF_ASSISTANCE_NEEDED);
        PRIVACY_SETTING_BUSINESS_MAP.put(SettingKeyCodeEnum.LAST_NAME, FIELD);
    }

    public static List<String> BUSINESS_INFO_MAP = new ArrayList<>();
    static {
        BUSINESS_INFO_MAP.add(FormConstant.PORTAL_INTAKE_QUESTION_BUSINESS);
        BUSINESS_INFO_MAP.add(FormConstant.PORTAL_INTAKE_QUESTION_EMAIL_ADDRESS);
        BUSINESS_INFO_MAP.add(FormConstant.QUESTION_BUSINESS_OPENING_DATE);
        BUSINESS_INFO_MAP.add(FormConstant.PORTAL_INTAKE_QUESTION_GENDER);
        BUSINESS_INFO_MAP.add(FormConstant.PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE);
        BUSINESS_INFO_MAP.add(FormConstant.PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE);
        BUSINESS_INFO_MAP.add(FormConstant.PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE_OTHER);
        BUSINESS_INFO_MAP.add(FormConstant.PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE_OTHER);
        BUSINESS_INFO_MAP.add(FormConstant.PORTAL_INTAKE_QUESTION_DESCRIBE_TYPE_OF_ASSISTANCE_NEEDED);
    }
}
