package com.formos.huub.domain.constant;

import java.util.ArrayList;
import java.util.List;

public final class MetricExportConstant {

    public static final String COLUMN_PORTAL_NAME = "Portal Name";
    public static final String COLUMN_CREATED_DATE = "Created Date";
    public static final String COLUMN_FIRST_NAME = "Your First Name";
    public static final String COLUMN_LAST_NAME = "Your Last Name";
    public static final String COLUMN_YOUR_EMAIL = "Your Email Address";
    public static final String COLUMN_YOUR_PHONE_NUMBER = "Your Phone Number";
    public static final String COLUMN_NAME_YOUR_BUSINESS = "Name of your business";

    // Header for application export data
    public static final String COLUMN_ADVISOR_NAME = "Advisor Name";
    public static final String COLUMN_VENDOR = "Vendor";
    public static final String COLUMN_APPOINTMENT_CATEGORY = "Appointment Category";
    public static final String COLUMN_APPOINTMENT_SERVICE = "Appointment Service";
    public static final String COLUMN_STATUS = "Status";
    public static final String COLUMN_START_DATE_TIME = "Start Date & Time";
    public static final String COLUMN_END_DATE_TIME = "End Date & Time";
    public static final String COLUMN_DESCRIPTION_LIKE_SUPPORT_FROM_ADVISOR = "As specific as possible, please describe what you'd like support from your advisor for?";
    public static final String COLUMN_URL_SHARE_YOUR_ADVISOR = "Please share any links/URLs/websites you'd like to share with your advisor.";
    public static final String COLUMN_APPOINTMENT_SERVICE_OUTCOME = "OUTCOMES: This requested support will help...";


    //Header for project export data
    public static final String COLUMN_PROJECT_TITLE = "Project Title";
    public static final String COLUMN_CATEGORY = "Category";
    public static final String COLUMN_SERVICE = "Service";
    public static final String COLUMN_SCOPE_OF_WORK = "Scope of Work";
    public static final String COLUMN_ESTIMATED_HOURS = "Estimated Hours";
    public static final String COLUMN_PROPOSED_START_DATE = "Proposed Start Date";
    public static final String COLUMN_ESTIMATED_COMPLETION_DATE = "Estimated Completion Date";
    public static final String COLUMN_RELATED_APPOINTMENT = "Related Appointment";
    public static final String COLUMN_RELATED_INVOICE = "Related Invoice #";
    public static final String COLUMN_REPORT = "Report #";

    // Header for  event registration export data
    public static final String COLUMN_EVENT_NAME = "Event Name";
    public static final String COLUMN_EVENT_DESCRIPTION = "Event Description";
    public static final String COLUMN_EVENT_START_DATE = "Event Start Date";

    // Header for course export data
    public static final String COLUMN_COURSE_NAME = "Course Name";
    public static final String COLUMN_COURSE_CATEGORY= "Course Category";
    public static final String COLUMN_DATE_ENROLLED = "Date Enrolled";
    public static final String COLUMN_DATE_COMPLETED = "Date Completed";
    public static final String COLUMN_USER_COURSE_RATING = "User Course Rating";
    public static final String COLUMN_NUMBER_OF_LESSONS_COMPLETED = "# of Lessons Completed";
    public static final String COLUMN_TOTAL_LESSONS = "Total number of lessons in course";

    // Header for invoice project and appointment
    public static final String COLUMN_INVOICE_NUMBER = "Invoice #";
    public static final String COLUMN_HOURS_COMPLETED = "Hours Completed";
    public static final String COLUMN_RATE = "Rate";
    public static final String COLUMN_COST = "Cost";
    public static final String COLUMN_ADVISOR = "Advisor";
    public static final String COLUMN_BUSINESS_OWNER_NAME = "Business Owner Name";
    public static final String COLUMN_BUSINESS_NAME = "Business Name";
    public static final String COLUMN_APPOINTMENT_DATE = "Appointment Date";
    public static final String COLUMN_PROJECT_COMPLETION_DATE = "Project Completion Date";

    public static final List<String> LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT = new ArrayList<>();

    static {
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_FIRST_NAME);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_LAST_NAME);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_EMAIL_ADDRESS);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_PHONE_NUMBER);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_JOB_TITLE);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_PREFER_CONTACTED);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_HEAR_ABOUT_PROGRAM);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_HEAR_ABOUT_PROGRAM_OTHER);

        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_BUSINESS);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_STATE_PROVINCE);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_CITY);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_COUNTRY);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_ZIPCODE);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_STREET_ADDRESS);

        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_STRUCTURE);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_REGISTRATION);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_OPENING_DATE);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_INDUSTRY_INFORMATION);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_REVENUE_INFORMATION_TOW_YEAR);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_REVENUE_INFORMATION_ONE_YEAR);

        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_EMPLOYEE_COUNT);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_HOME_BASED_LOCATION);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_HOW_MANY_LOCATIONS);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_HAVE_MORE_THAN_ONE_LOCATION_IN_CITY);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_DURATION);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.QUESTION_BUSINESS_STATUS);

        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_AGE_RANGE);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_GENDER);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_HOUSEHOLD_INCOME);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_HOW_MANY_PEOPLE);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_LANGUAGE_SPEAKING_OTHER);

        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_ETHNICITY);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_EDUCATION);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_MILITARY_AFFILIATION);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_LGBTQIA);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_DISABILITY_OR_DISABILITIES);

        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_DESCRIBE_ASSISTANCE);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_FIRST_PRIORITY_AREA_OTHER);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA);
        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_SECOND_PRIORITY_AREA_OTHER);

        LIST_QUESTION_BUSINESS_OWNER_INTAKES_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_WOULD_TOU_LIKE_APPLY_FREE_ASSISTANCE);

    }

    public static final List<String> LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT = new ArrayList<>();

    static {
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_BUSINESS);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_YOUR_EIN);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_YOUR_BUSINESS_LICENSE);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_DESCRIBE_TYPE_OF_ASSISTANCE_NEEDED);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_PREFERRED_ORGANIZATION_FOR_ASSISTANCE);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_1ST_PRIORITY_FOR_1_1_ASSISTANCE_OTHER);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_1ND_PRIORITY_OTHER);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_2ND_PRIORITY_FOR_1_1_ASSISTANCE_OTHER);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_TOPIC_AREAS_OF_INTEREST_FOR_2ND_PRIORITY_OTHER);
        LIST_QUESTION_TECHNICAL_ASSISTANCE_EXPORT.add(FormConstant.PORTAL_INTAKE_QUESTION_ADVISOR_SUPPORT_DESCRIPTION);
    }
    public static final List<String> LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT = new ArrayList<>();
    static {
        LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT.add(COLUMN_PORTAL_NAME);
        LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT.add(COLUMN_CREATED_DATE);
        LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT.add(COLUMN_FIRST_NAME);
        LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT.add(COLUMN_LAST_NAME);
        LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT.add(COLUMN_YOUR_EMAIL);
        LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT.add(COLUMN_NAME_YOUR_BUSINESS);
    }

    public static final List<String> LIST_HEADER_APPOINTMENTS_EXPORT = new ArrayList<>();

    static {
        LIST_HEADER_APPOINTMENTS_EXPORT.addAll(LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_ADVISOR_NAME);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_VENDOR);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_APPOINTMENT_CATEGORY);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_APPOINTMENT_SERVICE);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_STATUS);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_START_DATE_TIME);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_END_DATE_TIME);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_DESCRIPTION_LIKE_SUPPORT_FROM_ADVISOR);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_URL_SHARE_YOUR_ADVISOR);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_APPOINTMENT_SERVICE_OUTCOME);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_RELATED_INVOICE);
        LIST_HEADER_APPOINTMENTS_EXPORT.add(COLUMN_REPORT);
    }

    public static final List<String> LIST_HEADER_PROJECTS_EXPORT = new ArrayList<>();

    static {
        LIST_HEADER_PROJECTS_EXPORT.addAll(LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_ADVISOR_NAME);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_VENDOR);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_CATEGORY);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_SERVICE);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_STATUS);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_SCOPE_OF_WORK);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_ESTIMATED_HOURS);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_PROPOSED_START_DATE);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_ESTIMATED_COMPLETION_DATE);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_RELATED_INVOICE);
        LIST_HEADER_PROJECTS_EXPORT.add(COLUMN_REPORT);
    }

    public static final List<String> LIST_HEADER_EVENT_REGISTRATION_EXPORT = new ArrayList<>();

    static {
        LIST_HEADER_EVENT_REGISTRATION_EXPORT.addAll(LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT);
        LIST_HEADER_EVENT_REGISTRATION_EXPORT.add(COLUMN_EVENT_NAME);
        LIST_HEADER_EVENT_REGISTRATION_EXPORT.add(COLUMN_EVENT_DESCRIPTION);
        LIST_HEADER_EVENT_REGISTRATION_EXPORT.add(COLUMN_EVENT_START_DATE);
    }

    public static final List<String> LIST_HEADER_COURSES_EXPORT = new ArrayList<>();

    static {
        LIST_HEADER_COURSES_EXPORT.addAll(LIST_HEADER_COMMON_PERSONAL_STANDARD_EXPORT);
        LIST_HEADER_COURSES_EXPORT.add(COLUMN_COURSE_NAME);
        LIST_HEADER_COURSES_EXPORT.add(COLUMN_COURSE_CATEGORY);
        LIST_HEADER_COURSES_EXPORT.add(COLUMN_DATE_ENROLLED);
        LIST_HEADER_COURSES_EXPORT.add(COLUMN_DATE_COMPLETED);
        LIST_HEADER_COURSES_EXPORT.add(COLUMN_USER_COURSE_RATING);
        LIST_HEADER_COURSES_EXPORT.add(COLUMN_NUMBER_OF_LESSONS_COMPLETED);
        LIST_HEADER_COURSES_EXPORT.add(COLUMN_TOTAL_LESSONS);
    }

    public static final List<String> LIST_HEADER_INVOICES_EXPORT = new ArrayList<>();
    static {
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_INVOICE_NUMBER);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_HOURS_COMPLETED);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_RATE);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_COST);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_ADVISOR);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_BUSINESS_OWNER_NAME);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_BUSINESS_NAME);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_APPOINTMENT_DATE);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_PROJECT_COMPLETION_DATE);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_CATEGORY);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_SERVICE);
        LIST_HEADER_INVOICES_EXPORT.add(COLUMN_REPORT);
    }
}
