package com.formos.huub.domain.enums;

import com.fasterxml.jackson.annotation.JsonValue;
import com.formos.huub.framework.enums.CodeEnum;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum FeatureCodeEnum  implements CodeEnum {

    PORTALS("PORTALS", "PORTALS"),
    PORTALS_SETTING("PORTALS_SETTING", "PORTALS_SETTING"),
    PORTALS_GRANTS("PORTALS_GRANTS", "PORTALS_GRANTS"),
    PORTALS_BUSINESS_OWNERS("PORTALS_BUSINESS_OWNERS", "PORTALS_BUSINESS_OWNERS"),
    PORTALS_COMMUNITY_PARTNERS("PORTALS_COMMUNITY_PARTNERS", "PORTALS_COMMUNITY_PARTNERS"),
    PORTALS_WORK_PACKAGES("PORTALS_WORK_PACKAGES", "PORTALS_WORK_PACKAGES"),
    PORTALS_LEARNING_LIBRARY("PORTALS_LEARNING_LIBRARY", "PORTALS_LEARNING_LIBRARY"),
    PORTALS_CALENDAR_AND_EVENTS("PORTALS_CALENDAR_AND_EVENTS", "PORTALS_CALENDAR_AND_EVENTS"),
    PORTALS_REPORTS("PORTALS_REPORTS", "PORTALS_REPORTS"),
    PORTALS_MESSAGING("PORTALS_MESSAGING", "PORTALS_MESSAGING"),
    ABOUTS("ABOUTS", "ABOUTS"),
    PORTAL_WELCOME("PORTAL_WELCOME", "PORTAL_WELCOME"),
    FEATURES("FEATURES", "FEATURES"),
    PROGRAM_DETAILS("PROGRAM_DETAILS", "PROGRAM_DETAILS"),
    CUSTOMIZE("CUSTOMIZE", "CUSTOMIZE"),
    LOCATIONS("LOCATIONS", "LOCATIONS"),
    COMMUNITY_BOARDS("COMMUNITY_BOARDS", "COMMUNITY_BOARDS"),
    PORTAL_HOSTS("PORTAL_HOSTS", "PORTAL_HOSTS"),
    COMMUNITY_RESOURCE("COMMUNITY_RESOURCE", "COMMUNITY_RESOURCE"),
    FUNDING_DIRECTORY("FUNDING_DIRECTORY", "FUNDING_DIRECTORY"),
    COMMUNITY_ABOUT_PAGE("COMMUNITY_ABOUT_PAGE", "COMMUNITY_ABOUT_PAGE"),
    PORTAL_FUNDING_ABOUT("PORTAL_FUNDING_ABOUT", "PORTAL_FUNDING_ABOUT"),
    PORTAL_FUNDING_FUNDER_DETAILS("PORTAL_FUNDING_FUNDER_DETAILS", "PORTAL_FUNDING_FUNDER_DETAILS"),
    PORTAL_FUNDING_APPLICATION_DETAILS("PORTAL_FUNDING_APPLICATION_DETAILS", "PORTAL_FUNDING_APPLICATION_DETAILS"),
    LEARNING_LIBRARY("LEARNING_LIBRARY", "LEARNING_LIBRARY"),
    LEARNING_LIBRARY_ABOUT("LEARNING_LIBRARY_ABOUT", "LEARNING_LIBRARY_ABOUT"),
    LEARNING_LIBRARY_SPEAKERS("LEARNING_LIBRARY_SPEAKERS", "LEARNING_LIBRARY_SPEAKERS"),
    LEARNING_LIBRARY_STEPS_LESSONS("LEARNING_LIBRARY_STEPS_LESSONS", "LEARNING_LIBRARY_STEPS_LESSONS"),
    PORTALS_INTAKE_QUESTIONS("PORTALS_INTAKE_QUESTIONS", "PORTALS_INTAKE_QUESTIONS"),
    PORTALS_INTAKE_QUESTIONS_PROFILE("PORTALS_INTAKE_QUESTIONS_PROFILE", "PORTALS_INTAKE_QUESTIONS_PROFILE"),
    PORTALS_INTAKE_QUESTIONS_BUSINESS("PORTALS_INTAKE_QUESTIONS_BUSINESS", "PORTALS_INTAKE_QUESTIONS_BUSINESS"),
    PORTALS_INTAKE_QUESTIONS_DEMOGRAPHICS("PORTALS_INTAKE_QUESTIONS_DEMOGRAPHICS", "PORTALS_INTAKE_QUESTIONS_DEMOGRAPHICS"),
    PORTALS_INTAKE_QUESTIONS_ASSISTANCE_NEEDS("PORTALS_INTAKE_QUESTIONS_ASSISTANCE_NEEDS", "PORTALS_INTAKE_QUESTIONS_ASSISTANCE_NEEDS"),
    PORTALS_INTAKE_ADDITIONAL_QUESTIONS("PORTALS_INTAKE_ADDITIONAL_QUESTIONS", "PORTALS_INTAKE_ADDITIONAL_QUESTIONS"),
    TECHNICAL_ASSISTANCE_ADDITIONAL_QUESTIONS("TECHNICAL_ASSISTANCE_ADDITIONAL_QUESTIONS", "TECHNICAL_ASSISTANCE_ADDITIONAL_QUESTIONS");

    private final String value;

    private final String name;

    @JsonValue
    public String getValue() {
        return value;
    }
}
