package com.formos.huub.domain.enums;

import com.fasterxml.jackson.annotation.JsonValue;
import com.formos.huub.framework.enums.CodeEnum;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum FormCodeEnum implements CodeEnum {

    DEMOGRAPHICS("DEMOGRAPHICS", "DEMOGRAPHICS"),
    PORTAL_INTAKE_QUESTION_PROFILE("PORTAL_INTAKE_QUESTION_PROFILE", "PORTAL_INTAKE_QUESTION_PROFILE"),
    PORTAL_INTAKE_QUESTION_BUSINESS("PORTAL_INTAKE_QUESTION_BUSINESS", "PORTAL_INTAKE_QUESTION_BUSINESS"),
    PORTAL_INTAKE_QUESTION_DEMOGRAPHICS("PORTAL_INTAKE_QUESTION_DEMOGRAPHICS", "PORTAL_INTAKE_QUESTION_DEMOGRAPHICS"),
    PORTAL_INTAKE_QUESTION_ASSISTANCE_NEEDS("PORTAL_INTAKE_QUESTION_ASSISTANCE_NEEDS", "PORTAL_INTAKE_QUESTION_ASSISTANCE_NEEDS"),
    PORTAL_INTAKE_ADDITIONAL_QUESTION("PORTAL_INTAKE_ADDITIONAL_QUESTION", "PORTAL_INTAKE_QUESTION_ADDITIONAL"),
    TECHNICAL_ASSISTANCE_ADDITIONAL_QUESTION("TECHNICAL_ASSISTANCE_ADDITIONAL_QUESTION", "TECHNICAL_ASSISTANCE_ADDITIONAL_QUESTION"),
    PORTAL_INTAKE_SUPPORT_APPLICATIONS("PORTAL_INTAKE_SUPPORT_APPLICATIONS", "PORTAL_INTAKE_SUPPORT_APPLICATIONS"),
    PORTAL_ABOUT_SCREEN_CONFIGURATION("PORTAL_ABOUT_SCREEN_CONFIGURATION", "PORTAL_ABOUT_SCREEN_CONFIGURATION"),
    BOOKING_APPOINTMENT_WITH_TECHNICAL_ADVISOR("BOOKING_APPOINTMENT_WITH_TECHNICAL_ADVISOR", "BOOKING_APPOINTMENT_WITH_TECHNICAL_ADVISOR");

    private final String value;

    private final String name;

    @JsonValue
    public String getValue() {
        return value;
    }
}
