package com.formos.huub.domain.enums;

import com.fasterxml.jackson.annotation.JsonValue;
import com.formos.huub.framework.enums.CodeEnum;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum GroupCodeEnum  implements CodeEnum {

    CONSULTING_FEES("CONSULTING_FEES", "CONSULTING_FEES"),
    INFORMATION_AND_IDENTITY("INFORMATION_AND_IDENTITY", "INFORMATION_AND_IDENTITY"),
    PERSONAL_CHARACTERISTICS("PERSONAL_CHARACTERISTICS", "PERSONAL_CHARACTERISTICS"),
    PERSONAL_INFORMATION("PERSONAL_INFORMATION", "PERSONAL_INFORMATION"),
    BUSINESS_INFORMATION("BUSINESS_INFORMATION", "BUSINESS_INFORMATION"),
    MEMBER_BUSINESS_OWNER_PROFILE("MEMBER_BUSINESS_OWNER_PROFILE", "MEMBER_BUSINESS_OWNER_PROFILE"),
    MEMBER_BUSINESS_OWNER_BUSINESS("MEMBER_BUSINESS_OWNER_BUSINESS", "MEMBER_BUSINESS_OWNER_BUSINESS"),
    MEMBER_BUSINESS_OWNER_DEMOGRAPHICS("MEMBER_BUSINESS_OWNER_DEMOGRAPHICS", "MEMBER_BUSINESS_OWNER_DEMOGRAPHICS"),
    MEMBER_BUSINESS_OWNER_ASSISTANCE_NEEDS("MEMBER_BUSINESS_OWNER_ASSISTANCE_NEEDS", "MEMBER_BUSINESS_OWNER_ASSISTANCE_NEEDS");

    private final String value;

    private final String name;

    @JsonValue
    public String getValue() {
        return value;
    }
}
