package com.formos.huub.domain.enums;

import com.fasterxml.jackson.annotation.JsonValue;
import com.formos.huub.framework.enums.CodeEnum;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum NotificationTypeEnum implements CodeEnum {
    NEW_FOLLOWER("NEW_FOLLOWER", "NEW_FOLLOWER"),
    NEW_ACTIVITY_POSTED_FOLLOWER("NEW_ACTIVITY_POSTED_FOLLOWER", "NEW_ACTIVITY_POSTED_FOLLOWER"),
    NEW_MENTION("NEW_MENTION", "NEW_MENTION"),
    NEW_MESSAGE("NEW_MESSAGE", "NEW_MESSAGE"),
    SCHEDULE_APPOINTMENT("SCHEDULE_APPOINTMENT", "schedule.appointment"),
    RESCHEDULE_APPOINTMENT("RESCHEDULE_APPOINTMENT", "reschedule.appointment"),
    CANCEL_APPOINTMENT("CANCEL_APPOINTMENT", "cancel.appointment"),
    UPDATE_APPOINTMENT("UPDATE_APPOINTMENT", "update.appointment"),
    POST_NOTIFY_ALL("POST_NOTIFY_ALL", "POST_NOTIFY_ALL"),
    UPDATE_MANAGE_GROUP("UPDATE_MANAGE_GROUP", "UPDATE_MANAGE_GROUP"),
    REJECTED_JOIN_GROUP_REQUEST("REJECTED_JOIN_GROUP_REQUEST", "REJECTED_JOIN_GROUP_REQUEST"),
    ACCEPTED_JOIN_GROUP_REQUEST("ACCEPTED_JOIN_GROUP_REQUEST", "ACCEPTED_JOIN_GROUP_REQUEST"),
    PROMOTED_MODERATOR("PROMOTED_MODERATOR", "PROMOTED_MODERATOR"),
    PROMOTED_ORGANIZER("PROMOTED_ORGANIZER", "PROMOTED_ORGANIZER"),
    FLAG_POST_NOTIFY("FLAG_POST_NOTIFY", "FLAG_POST_NOTIFY"),
    RESTRICT_MEMBER("RESTRICT_MEMBER", "RESTRICT_MEMBER"),
    SYSTEM("SYSTEM", "SYSTEM"),
    NEW_COMMENT("NEW_COMMENT", "NEW_COMMENT"),
    NEW_POST("NEW_POST", "NEW_POST"),
    GROUP_INVITATIONS_REQUEST("GROUP_INVITATIONS_REQUEST", "GROUP_INVITATIONS_REQUEST"),
    PASSWORD_CHANGED("PASSWORD_CHANGED", "PASSWORD_CHANGED");

    private final String value;
    private final String name;

    @JsonValue
    public String getValue() {
        return value;
    }
}
