package com.formos.huub.domain.enums;

import com.fasterxml.jackson.annotation.JsonValue;
import com.formos.huub.framework.enums.CodeEnum;
import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum SettingKeyCodeEnum implements CodeEnum {

    ENABLE_NOTIFICATIONS("ENABLE_NOTIFICATIONS", "ENABLE_NOTIFICATIONS"),
    MEMBER_MENTION("MEMBER_MENTION", "MEMBER_MENTION"),
    PASSWORD_CHANGED("PASSWORD_CHANGED", "PASSWORD_CHANGED"),
    MEMBER_REPLIES_POST_COMMENT("MEMBER_REPLIES_POST_COMMENT", "MEMBER_REPLIES_POST_COMMENT"),
    NEW_POST_MEMBER_FOLLOWING("NEW_POST_MEMBER_FOLLOWING", "NEW_POST_MEMBER_FOLLOWING"),
    MEMBER_STARTS_FOLLOWING("MEMBER_STARTS_FOLLOWING", "MEMBER_STARTS_FOLLOWING"),
    DETAILS_GROUP_MANAGE_UPDATED("DETAILS_GROUP_MANAGE_UPDATED", "DETAILS_GROUP_MANAGE_UPDATED"),
    PROMOTED_IN_GROUP("PROMOTED_IN_GROUP", "PROMOTED_IN_GROUP"),
    RECEIVE_INVITE_JOIN_GROUP("RECEIVE_INVITE_JOIN_GROUP", "RECEIVE_INVITE_JOIN_GROUP"),
    MEMBER_REQUEST_JOIN_GROUP("MEMBER_REQUEST_JOIN_GROUP", "MEMBER_REQUEST_JOIN_GROUP"),
    REQUEST_JOIN_GROUP_ACCEPTED("REQUEST_JOIN_GROUP_ACCEPTED", "REQUEST_JOIN_GROUP_ACCEPTED"),
    REQUEST_JOIN_GROUP_REJECTED("REQUEST_JOIN_GROUP_REJECTED", "REQUEST_JOIN_GROUP_REJECTED"),
    RECEIVE_NEW_GROUP_MESSAGE("RECEIVE_NEW_GROUP_MESSAGE", "RECEIVE_NEW_GROUP_MESSAGE"),
    NEW_POST_IN_GROUP_SUBSCRIBED("NEW_POST_IN_GROUP_SUBSCRIBED", "NEW_POST_IN_GROUP_SUBSCRIBED"),
    NEW_MEETING_SCHEDULED_IN_GROUP("NEW_MEETING_SCHEDULED_IN_GROUP", "NEW_MEETING_SCHEDULED_IN_GROUP"),
    RECEIVE_NEW_PRIVATE_MESSAGE("RECEIVE_NEW_PRIVATE_MESSAGE", "RECEIVE_NEW_PRIVATE_MESSAGE"),
    RECEIVE_NEW_CONNECTION_REQUEST("RECEIVE_NEW_CONNECTION_REQUEST", "RECEIVE_NEW_CONNECTION_REQUEST"),
    CONNECTION_REQUEST_ACCEPTED("CONNECTION_REQUEST_ACCEPTED", "CONNECTION_REQUEST_ACCEPTED"),

    HUUB_PORTAL("HUUB_PORTAL", "HUUB_PORTAL"),
    COMPANY("COMPANY", "COMPANY"),
    BUSINESS_WEBSITE("BUSINESS_WEBSITE", "BUSINESS_WEBSITE"),
    DATE_BUSINESS_OPENED("DATE_BUSINESS_OPENED", "DATE_BUSINESS_OPENED"),
    GENDER("GENDER", "GENDER"),
    FIRST_PRIORITY_ASSISTANCE("FIRST_PRIORITY_ASSISTANCE", "FIRST_PRIORITY_ASSISTANCE"),
    SECOND_PRIORITY_ASSISTANCE("SECOND_PRIORITY_ASSISTANCE", "SECOND_PRIORITY_ASSISTANCE"),
    WOULD_LIKE_SUPPORT_ON("WOULD_LIKE_SUPPORT_ON", "WOULD_LIKE_SUPPORT_ON"),
    FIRST_NAME("FIRST_NAME", "FIRST_NAME"),
    LAST_NAME("LAST_NAME", "LAST_NAME"),
    USERNAME("USERNAME", "USERNAME"),

    PRIVACY_OPTIONS("PRIVACY_OPTIONS", "PRIVACY_OPTIONS"),
    GROUP_INVITATIONS("GROUP_INVITATIONS", "GROUP_INVITATIONS"),
    GROUP_POSTS("GROUP_POSTS", "GROUP_POSTS"),
    GROUP_PHOTOS("GROUP_PHOTOS", "GROUP_PHOTOS"),
    GROUP_DOCUMENTS("GROUP_DOCUMENTS", "GROUP_DOCUMENTS"),
    GROUP_VIDEOS("GROUP_VIDEOS", "GROUP_VIDEOS"),
    GROUP_MESSAGES("GROUP_MESSAGES", "GROUP_MESSAGES");

    private final String value;

    private final String name;

    @JsonValue
    public String getValue() {
        return value;
    }
}
